export const themes = {
  dark: {
    app: "App dark",
    title: "title text dark",
    moon: "moon",
    todoForm: "todo-form dark",
    todoInput: "todo-input dark",
    appSummary: "app-summary dark",
    appSumary: "app-summary dark",
    todoSection: "todo-section dark",
    todoList: "todo-list dark",
    todoItem: "todo-item dark",
    todoCheckbox: "todo-checkbox dark",
    sortControl: "sort-control dark",
    darkModeButton: "btn-darkMode dark",
    text: "text dark",
    todoItemInput: "todo-item-input dark",
  },
  light: {
    app: "App",
    title: "title text",
    moon: "",
    todoForm: "todo-form",
    todoInput: "todo-input",
    appSummary: "app-summary",
    appSumary: "app-summary",
    todoSection: "todo-section",
    todoList: "todo-list",
    todoItem: "todo-item",
    todoCheckbox: "todo-checkbox",
    sortControl: "sort-control",
    darkModeButton: "btn-darkMode",
    text: "text",
    todoItemInput: "todo-item-input",
  },
};
